### PR TITLE
Caching Tweaks

### PR DESCRIPTION
**Pull request by jonsmithers**
So, it seems that the service worker cache mainly just prevents me from getting updated versions of the app. It's not very helpful (I'm in a weird state right now where `index.html` is up to date but `index.js` is old). And I think we're doing it wrong. From I remember studying, you're not supposed to cache `index`. You cache everything _except_ `index.html`, and you append sha's to those filenames for when you update and want to bypass the cache.

I think we should disable caching and re-enable when we can do it correctly.

### CODE REVIEW

**Comment by dumbbillyhardy** [comment]
the cache is supposed to incorporate versioning, so if we don't bump the version, then we will definitely have problems with old files. Have you tried incrementing the version? In the background it will then cache the new files and once all tabs running the app are closed, the new cache will take effect.

**Comment by jonsmithers** [comment]
@billy-hardy I tried bumping the `package.json` version just now. I'm still in the state where `index.html` is up to date but `index.js` is old, except now the version discrepancy is wider.

**Comment by jonsmithers** [comment]
Oh, looking at the code, I see how that's supposed to work... not sure why it doesn't

**Comment by jonsmithers** [comment]
How about we use the git sha instead of the package version for the cache name? That way we never have to bump it manually.

**Pull request merged**
